set echo off
set feedback off
set linesize 100
set pagesize 0
set sqlprompt ''
set trimspool on
SPOOL genned_sequences.sql;
-- Write the Sequence DROP statements
SELECT 'DROP SEQUENCE MNR.TEST_SECTION_TRACKING_SEQ;' FROM DUAL;
-- configuration classes
SELECT 'DROP SEQUENCE MNR.HIBERNATE_SEQUENCE;' FROM DUAL;
--
-- 
SELECT 'CREATE SEQUENCE TEST_SECTION_TRACKING_SEQ MINVALUE 1 START WITH ' || MNR.TEST_SECTION_TRACKING_SEQ.NEXTVAL || ' INCREMENT BY 1 CACHE 20;' FROM DUAL;
-- 
SELECT 'CREATE SEQUENCE HIBERNATE_SEQUENCE MINVALUE 1 START WITH ' || MNR.HIBERNATE_SEQUENCE.NEXTVAL || ' INCREMENT BY 1 CACHE 20;' FROM DUAL;

SELECT 'EXIT;' FROM DUAL;
SPOOL OFF;
exit;
